apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ytjl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ytjl
    app.kubernetes.io/part-of: ci1t-830-0071-app
  name: devfile-sample-ytjl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ytjl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ytjl
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0071-tenant/ci1t-830-0071-app/devfile-sample-ytjl@sha256:11e34a236406b04fe06036d95d7bde72b960e425a35b837d5e243d9a98c13870
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
